= Контрольная работа №3: maybe
:icons: font
:table-caption!:
:example-caption!:
:source-highlighter: highlightjs
:revealjs_hash: true
:customcss: https://rawcdn.githack.com/fedochet/asciidoc-revealjs-online-converter/7012d6dd12132363bbec8ba4800272ceb6d0a3e6/asciidoc_revealjs_custom_style.css
:revealjs_theme: blood
:stylesheet: main.css
:toc:
:toclevels: 4


== Замечания

* Решение должно быть выполнено в namespace `control_03`
** не захламляйте при этом этот namespace:
** детали реализации стоит спрятать во вложенный namespace (`details`, например)
* тесты есть на каждый пункт задания — см CMakeLists.txt

ifdef::backend-revealjs[=== !]

* одна из ключевых техник для выполнения работы — хранение объекта в определенном буффере
** вспомните про placement new, явный вызов деструктора, выравнивание данных —
работу с памятью надо реализровать самостоятельно
** в работе нельзя использовать std::variant

== Предыстория

Иногда полезно иметь признак присутствия, готовности или инициализации объекта — обозначим такую оберку за `maybe<T>` и рассмотрим несколько примеров использования

=== Функция с необязательным результатом

* через возвращаемое значение-флаг (ok/not ok)
```c++
int computeIfPossible(const MyStruct& param, SomeResultType& out) {
    if (!IsOk(param)) { return 0; }

    out = Compute(param);
    /* ... */
    return 1;
}


SomeResultType computeResult;   // _default_
if (computeIfPossible(param, computeResult)) {
    /* computeResult is ready */
} else {
    /* computeResult is not ready, _default_ */
}
```

ifdef::backend-revealjs[=== !]

* через maybe<SomeResultType>:
```c++
maybe<SomeResultType> computeIfPossible(const MyStruct& param) {
    if (!IsOk(param)) { return {}; }   // does *not* create SomeResultType

    SomeResultType out = Compute(param);
    /* ... */
    return out;
}


maybe<SomeResultType> computeResult = computeIfPossible(param);
if (computeResult) {
    /* computeResult is ready */
    SomeResultType &result = computeResult.value();
} else {
    /* computeResult is not ready */
    /* computeResult.value() is *not* a valid object, not created */
}
```

=== Отложенная инициализация поля класса

```c++
class Reader {
    Input source;
    maybe<Buffer> buf;

public:
    Reader()
        : source{GetSource()}
        , buf{}     // no buffer object created until reading
    {}

    void Start() {  // time to read -> call this method
        buf = GetOneOfLimitedBuffers();  // Buffer is created
    }

    /* ... */
};

```

== Семантика maybe<T>

* `maybe<T>` - обертка над значением типа T, хранящая значение этого типа или признак его отсутствия
* в каждый момент времени в maybe:
** либо есть значение типа T
** либо он не содержит никакое значение T

ifdef::backend-revealjs[=== !]

Чем-то похоже на умный указатель, например, `unique_ptr<T>` (хранящий значение-адрес _или_ значение-nullptr) — но есть и отличия:

* maybe *не выделяет* динамическую память под объект
* память необходимого размера (для хранения значения T) находится *внутри* maybe<T>
** `sizeof(maybe<T>) >= sizeof(T)` в любой момент времени

ifdef::backend-revealjs[=== !]

* если создать пустой maybe<T> (default ctor), то объект типа T создаваться в этот момент *не будет*
* он создастся лишь в тот момент, когда maybe<T> будет проинициализирован значением типа Т (или аргументами для его создания - см. задачу #3)
** т.е. всегда есть буффер для хранения, не всегда _на нем_ существует объект

== Задача #1 [1.5 балла]

Делаем `maybe<T>` — шаблонный класс и основные методы, перечисленные ниже

ifdef::backend-revealjs[=== !]

* Конструкторы maybe<T>
** Дефолтный: `maybe<T>` создается пустым. `maybe::has_value` в таком случае возвращает false
** Копирования от `maybe<T>`: класс Т сам при этом должен иметь собственный доступный конструктор копирования
** От объекта типа T: класс Т сам при этом должен иметь собственный доступный конструктор копирования. Конструктор implicit
** Move-конструктор (от `maybe<T>`): класс Т сам при этом должен иметь собственный доступный move-конструктор
** От rvalue-ссылки на объект типа T: класс Т сам при этом должен иметь собственный доступный move-конструктор. Конструктор implicit

ifdef::backend-revealjs[=== !]

* Функции-модификаторы:
** `reset()`: освобождает значение maybe (удаляет; если оно в нем было)
** `reset` с аргументом типа T: освобождает текущее значение maybe (если оно в нем было) + сохраняет в нем значение, переданное в качестве аргумента. Не должно быть более одного копирования типа T
*** ожидается именно удаление + конструирование

ifdef::backend-revealjs[=== !]

* Функции доступа
** `value()`, константная + неконстантая версии: возвращает ссылку на содержимое maybe (ссылка должна быть соответствующей константности)
*** если maybe<T> не содержит значение — это UB, дополнительных обработок не требуется
** `has_value()`: возвращает true, если maybe<T> содержит значение, и false иначе

ifdef::backend-revealjs[=== !]

* Операторы
** Присваивания: всегда те же, что и конструкторы копирования
** Приведения к условному выражению (нужно безопасное приведение)

=== Требования к типу T
* Единственное требование к типу T - у него можно вызвать деструктор
* Конструктор копирования требуется только, если соответствующий конструктор или оператор присваивания вызывается у maybe<T>

== Задача #2 [1 балл]

* В C++ указатели, из-за возможности использования nullptr, нативно обладают семантикой maybe
* => договоримся об оптимизации: для типов-указателей maybe заиспользуем nullptr как признак отсутствия (профит: объект не будет занимать больше памяти, чем сам указатель)
** для прочих типов `maybe<T>` имеет больший размер, чем сам T, т.к. хранит еще и признак наличия объекта
** NB: если обертка хранит указатель (`maybe<T*>`), она никак *не управляет* этой памятью — *не* делает подчисток объекта `T` через delete и проч.
* `value() const` при этом возвращает копию хранящегося адреса

== Задача #3 [0.5 балла]

Проблема с классами-обертками заключается в том, что зачастую приходится создавать временные объекты, которые приходится копировать:
```c++
maybe<MyClass> mb(MyClass{arg1, arg2, ...});
```

* Но MyClass может не иметь конструкторов копирования/move-конструкторов
* Обработаем этот случай, добавим:

ifdef::backend-revealjs[=== !]

1. Метод `emplace`, инициализирующий внутреннее значение напрямую переданными аргументами

* он не должен создавать никаких временных объектов `MyClass`
* меняется только внутреннее значение maybe-обертки
** объект конструируется от переданных в метод аргументов
* аргументы передаются идеально

2. Специальная форма конструктора `maybe(in_place_t, ...)`:

* таким же образом передаются аргументы на конструирование значения внутри
* нужна идеальная передача аргументов после `in_place_t` (сам он игнорируется)
* объект `in_place_t` должен быть глобальным


ifdef::backend-revealjs[=== !]

Так фрагмент кода выше может быть преобразован в:

```c++
// one object is created in mb (it's new value)
maybe<MyClass> mb{in_place_t, arg1, arg2, ...};

// another object is created in mb
// this new value replaces the old one
mb.emplace(arg0);
```

В таком случае объект MyClass не будет копироваться (и даже может не иметь доступного конструктора копирования), а будет создаваться внутри maybe<T> непосредственно из аргументов {arg1, arg2, …} или {arg0}
