= Задача: set
:icons: font
:table-caption!:
:example-caption!:
:source-highlighter: highlightjs
:revealjs_hash: true
:customcss: https://gistcdn.githack.com/fedochet/4ee0f4a2224ecd29a961082a0c63c020/raw/18c107982aba90bb94194c0ac3a8a5ca9bad6782/asciidoc_revealjs_custom_style.css
:revealjs_theme: blood
:stylesheet: main.css

== Постановка задачки
Разработайте библиотечный класс множества (`set`), содержащий уникальные упорядоченные элементы произвольного типа по значению. Класс во многом схож со стандартным `std::set`

Ваш класс должен предоставлять возможности по вставке, удалению и поиску элемента. Для __рандомизированных__ по значению запросов трудоемкость должны быть `O(logN)` — это означает, что сбалансированное дерево поиска писать не надо, достаточного обычного

Для доступа к элементам множества разработайте класс `element` (похожий на `set::iterator`) — обладает семантикой указателя для доступа к значению

* NB: `element` дает доступ лишь к константному значению, т.к. элементы множества изменять нельзя — это может привести к нарушению порядка элементов

ifdef::backend-revealjs[=== !]

Задание разбито на части, рекомендуем выполнять их последовательно (всего на 3.5 балла). Также рекомендуем выполнить несколько заданий, т.к. ошибки могут приводить к снижению оценки

Дополнительные требования:

* Поместите вашу реализацию множества в `namespace exam` и файл `set.hpp`. Непосредственно в namespace exam не должно быть больше других классов. Если потребуется, помещайте детали реализации во внутренний `namespace details` (или внутрь класса)

* Можно пользоваться стандартной библиотекой, но не ее компонентами для реализации set’a, конечно (`tree`, `set`, `iterator`)

* Не должно быть утечек памяти + код должен компилироваться без warning’ов

** в начале `smoke_test` закомментированы отдельные define'ы на подзадачи — раскрывайте их по мере решения

* Программа должна быть реализована самостоятельно без использования решений коллег и внешних ресурсов

== Базовая часть [1.5 балла]

Реализовать `set`:

* Шаблонный класс, параметризуемый типом значения
** это же значение является и ключом, аналогично `std::set`
** для вставки элемента тип значения должен быть копируемым и сравнимым по оператору `<` (также используется в поиске)

* Класс должен декларировать типы для `key_type`, `value_type`, `element`, `size_type`
* Конструктор по умолчанию
* Копирование и перемещение пока должны быть недоступны (изменится в одном из следующих заданий)

=== Нужные методы

* `empty` и `size`, возвращающие признак пустого множества и его размер соответственно
* `clear`
* Константный метод `end` - возвращает element, следующий за последним. Используется для проверки того, что искомый элемент не найден
* `find` по ключу: возвращает соответствующий описательный объект element
** в случае неуспеха, этот элемент равен `end()`
* `insert` — вставляет значение. Возвращает пару `(element, bool)` аналогично `std::set::insert` (см. https://en.cppreference.com/w/cpp/container/set/insert[описание])
** нужно поддержать две формы метода: принимающий константную ссылку на элемент и rvalue-ссылку
* Внешняя функция `swap`

=== Про `element` из `set`

Все операции для `element` действительны лишь для разыменовываемых `element`’ов, ссылающихся на значения из текущего `set`’a. В противном случае - UB

== Копирование и перемещение [0.5 балла]

Дополните ваш set возможностью копирования и перемещения:

* Copy ctor/assign: подразумевается deep copy
* Move ctor/assign: данные "передаются" в this, множество-аргумент other должно остаться пустым

== Custom Comparator [0.5 балла]

Дополните ваш `set` возможностью задать произвольный компаратор (аналогично `std::set`). Обратите внимание, что:

* компаратор надо добавить как шаблонный параметр с дефолтным значением `std::less`
* объект-компаратор можно передать в конструктор множества (потребуется специальная версия от одного аргумента этого шаблонного типа, безопасная)
* если множество было создано без явно переданного объекта-компаратора (и не через копирование) — надо использовать дефолтно-сконструированную версию объекта этого типа
* объект-компаратор надо хранить внутри объекта-множества

Компаратор отразится как на функциональности вставки, так и поиска. Требование по сравнимости оператором < определяется теперь компаратором

== Iterators [0.5 балла]

Дополните ваш класс `element` возможностью итерироваться по множеству в прямом направлении. А именно:

* В `set` появляется новая константная функция `begin()` для доступа к первому по порядку значению множества
* В `element` появляются операторы префиксного и постфиксного инкремента

== Erase [0.5 балла]
Добавьте в set две функции `erase`:

* `erase` по ключу. Возвращает `bool` - признак того, был ли удален элемент или нет
* `erase` по `element`’у. Возвращает element на следующее после удаляемого элемента значение
